### ISSUE TITLE
Ensembl Exon and Transcripts need a field containing the ensembl id without a prefix

### ISSUE THREAD

**Issue by prismofeverything** [biostream/bmeg-etl#21]

**Comment by prismofeverything** [comment]
Currently the `id` field looks like this:

    exon:ENSE00002234944

But this value does not appear without a prefix, which would be necessary to look this vertex up directly given the ensembl id.

**Comment by kellrott** [comment]
Fixed in https://github.com/biostream/ensembl-transform/commit/e5d99f1c8d67fe699af3319a8cf471be1be9a30b

**Comment by prismofeverything** [comment]
Awesome thanks. Those will be recomputed next run.

**Comment by kellrott** [comment]
From Protograph `ensembl/ensembl.Gene.Vertex.json`

```
{"label":"Gene","gid":"gene:ISG15","data":{"id":"gene:ENSG00000187608","symbol":"ISG15",
```
`gid` should be extracted from  `id` rather then `symbol`

**Comment by kellrott** [comment]
This is fixed, right?

**Comment by prismofeverything** [comment]
Yes! Looks like it.
