### ISSUE TITLE
empty from field in ccle.GeneExpression.Edge.json

### ISSUE THREAD

**Issue by kellrott** [biostream/bmeg-etl#23]
```
{"gid":"()--expressionLevel->(gene:ENSG00000252876.1)","fromLabel":"Biosample","from":"","label":"expressionLevel","toLabel":"Gene","to":"gene:ENSG00000252876.1","data":{"gene":"ENSG00000252876.1","level":0.0,"sample":""}}
```

**Comment by kellrott** [comment]
Also, is the "gene" field in data  unnecessary (already have that in the `to` field)

**Comment by kellrott** [comment]
Probably related, 0.01ccle.GeneExpression.Vertex.json has 
```
{"label":"GeneExpression","gid":"geneExpression::GeneExpression",
```
which should be an invalid gid

**Comment by buchanae** [comment]
> Also, is the "gene" field in data unnecessary (already have that in the to field)?

#62 removes the `data.gene` field
