### ISSUE TITLE
GTEX Transform

### ISSUE THREAD

**Issue by kellrott** [biostream/bmeg-etl#36]
https://github.com/biostream/gtex-transform

**Comment by prismofeverything** [comment]
I have encountered an issue with this here: https://github.com/biostream/gtex-transform/issues/2

**Comment by buchanae** [comment]
FYI, I'm working on updating the gtex transform. It looks like the same format as the ccle data, so I'm trying to reuse that code.

**Comment by prismofeverything** [comment]
Now we just need to write the gtex process entry.

**Comment by kellrott** [comment]
Change the BioSample id using files 
 - GTEx_Data_V6_Annotations_SampleAttributesDS.txt
 - GTEx_Data_V6_Annotations_SubjectPhenotypesDS.txt

The Biobank file lists stuff in the freezer, not samples that were sequenced.
