### ISSUE TITLE
G2P GID construction

### ISSUE THREAD

**Issue by kellrott** [biostream/bmeg-etl#40]
The GID created for the the biostream G2P records doesn't seem to reflect where the evidence comes from
```
{"label":"Evidence","gid":"evidence:A,HLA-A:Lymphoreticular tumour",
```
Seems to be a combo of the genotype and the disease. But there could be multiple pieces of evidence connected with association in this disease context.

**Comment by bwalsh** [comment]
https://github.com/bmeg/ratify/pull/2
