### ISSUE TITLE
GeneExpression.Edge has `level.float`

### ISSUE THREAD

**Issue by bwalsh** [biostream/bmeg-etl#48]
https://github.com/biostream/bmeg-etl/blob/master/bmeg.protograph.yaml#L239

yaml defines field name as `level.float` 

but  data record has `level`.

Should the record be flagged as an error, or should the config yaml be changed?

```
{"gid":"()--expressionLevel->(gene:ENSG00000215811.3)","fromLabel":"Biosample","from":"","label":"expressionLevel","toLabel":"Gene","to":"gene:ENSG00000215811.3","data":{"gene":"ENSG00000215811.3","level":0.106453105807304,"sample":""}}
```

**Comment by prismofeverything** [comment]
Hey Brian,

This is actually working as intended. In the README for protograph there is a description of typed fields. Basically, if the field has a `*.float` or `*.int` it will be emitted as that type. This is probably something we should validate. In the example above, it looks like `level` is coming through as a `float`, which is correct.

**Comment by prismofeverything** [comment]
Though, it looks like the `sample` field is blank, which is an error.

**Comment by bwalsh** [comment]
thanks.

>Though, it looks like the sample field is blank, which is an error.
yes, that I catch...
