### ISSUE TITLE
bioschemas inconsistent file naming

### ISSUE THREAD

**Issue by bwalsh** [biostream/bmeg-etl#49]
The files within biostream/biostream are inconsistent in that the expected pattern is xxx.[LABEL].json  where `xxx` is the project

For example see ccle

![image](https://user-images.githubusercontent.com/47808/34786971-9355d608-f5ea-11e7-80d6-0eb53b9bce82.png)

https://github.com/biostream/bmeg-etl/blob/master/bmeg.processes.yaml#L53-L55

**Comment by buchanae** [comment]
How about we leave off the project prefix from the filenames, since it already matches the directory name?

**Comment by bwalsh** [comment]
See biostream/protograph,  all the files there are consistently named.

**Comment by prismofeverything** [comment]
I agree, if all files are named consistently then we know the source even if the file appears separately from the object store.

I can update this in the `bmeg.processes.yaml` file.

**Comment by prismofeverything** [comment]
PR here: https://github.com/biostream/bmeg-etl/pull/50
