### ISSUE TITLE
Data consistency

### ISSUE THREAD

**Issue by prismofeverything** [biostream/bmeg-etl#75]
TCGA: CNACallset has spurious prefixes:

Vertex:
```{"label":"CNACallSet","gid":"cnaCallSet:tcga-cna:8efb4f70-fc31-42d6-8e99-b95069c771a4","data":{"bioSampleId":"tcga:8efb4f70-fc31-42d6-8e99-b95069c771a4","id":"tcga-cna:8efb4f70-fc31-42d6-8e99-b95069c771a4"}}```
Edge:
```{"gid":"(cnaCallSet:tcga-cna:8efb4f70-fc31-42d6-8e99-b95069c771a4)--cnaCallSetOf->(biosample:)","fromLabel":"CNACallSet","from":"cnaCallSet:tcga-cna:8efb4f70-fc31-42d6-8e99-b95069c771a4","label":"cnaCallSetOf","toLabel":"Biosample","to":"biosample:","data":{}}```

CNASegment has spurious prefixes, also the value should not be in the GID:
```{"label":"CNASegment","gid":"cnaSegment:tcga-cna:68f80d6b-1e4c-47e6-bcde-aace6305c555:X:251810:152846040:0.0020000000949949026","data":{"end":152846040,"callSetId":"tcga-cna:68f80d6b-1e4c-47e6-bcde-aace6305c555","value":0.0020000000949949026,"start":251810,"referenceName":"X"}}```

**Comment by prismofeverything** [comment]
TCGA: DrugTherapy edges to not all have compound ids (though some have names):

```{"gid":"(individual:8869000d-09d7-465a-ac32-54d1935c43e7)--drugTherapyFrom->(compound:36462)","fromLabel":"Individual","from":"individual:8869000d-09d7-465a-ac32-54d1935c43e7","label":"drugTherapyFrom","toLabel":"Compound","to":"compound:36462","data":{"drugName":"Etoposide","pubchemId":"36462","id":"3c971d88-ea87-4f2f-893c-b7bb558c402e","individualId":"8869000d-09d7-465a-ac32-54d1935c43e7","name":"TCGA-86-8075-D41680"}}```

**Comment by kellrott** [comment]
Yes, not all of the TCGA drug data was mapped to a compound id. They are text records, with misspellings and names of things that aren't in pubchem. The current mapping is https://github.com/biostream/gdc-transform/blob/master/tcga_pubchem.map

**Comment by prismofeverything** [comment]
A `source` property must be added to the following schemas to make everything consistent:

* Biosample
* CallSet
* ResponseCurve (source of the sample)
* GeneExpression
* CNACallSet
* CNASegment

**Comment by prismofeverything** [comment]
Okay I think I've fixed all these, we will see in the next run.

**Comment by prismofeverything** [comment]
Found a new issue where two of the `ResponseCurve` transforms (ccle and gdsc) are using the old schema (with a single `compound` field) while ctdd is using the new schema (with the plural `compounds` field).

**Comment by prismofeverything** [comment]
Fixed.
