### ISSUE TITLE
G2P.Features expressed as BMEG.Variants

### ISSUE THREAD

**Issue by bwalsh** [biostream/bmeg-etl#82]
@kellrott @prismofeverything 

This was confusing - "Multiple alternate alleles are possible." - Shouldn't those be separate variants?
https://github.com/biostream/schemas/blob/master/proto/bmeg/variants.proto#L190-L196

This [code](https://github.com/ohsu-comp-bio/g2p-aggregator/commit/3883d1aa880e2634b3484e0faaba8c08bb38173a#diff-4ef9324b27e0bc2acf308676a31487f7R62)  & [test](https://github.com/bmeg/ratify/blob/g2p/tests/test_biostream.py#L115-L126)  now ensures that ref and alt are transformed correctly.

However, we should clarify/refactor BMEG.Variants

**Comment by bwalsh** [comment]
Subsequent discussion w/ Kyle - perhaps we should map to [GA4GH.Feature](https://github.com/ga4gh/ga4gh-schemas/blob/master/src/main/proto/ga4gh/sequence_annotations.proto#L30) and bring that into BMEG

**Comment by bwalsh** [comment]
@prismofeverything - I've updated `Variant.json` in biostreams.  It still uses `Variant`, but now 'reference_bases' and 'alternate_bases' are present.

![image](https://user-images.githubusercontent.com/47808/36048291-9180a568-0d93-11e8-9980-fcf7fc764bfd.png)

**Comment by prismofeverything** [comment]
Cool, this is what I would expect. I think we should have a powwow on the variant schema here soon.
