### ISSUE TITLE
DrugTherapy Edges with no CID format incorrectly

### ISSUE THREAD

**Issue by kellrott** [biostream/bmeg-etl#94]
In the case that there is no `pubchemId` in the record, the `to` field is incorrectly formatted. Example

```
{
	"gid": "(individual:cf0a3f38-5850-44e1-8574-808bd37d84a3)--drugTherapyFrom->(compound:)",
	"fromLabel": "Individual",
	"from": "individual:cf0a3f38-5850-44e1-8574-808bd37d84a3",
	"label": "drugTherapyFrom",
	"toLabel": "Compound",
	"to": "compound:",
	"data": {
		"name": "TCGA-E9-A22D-D29927",
		"individualId": "cf0a3f38-5850-44e1-8574-808bd37d84a3",
		"source": "tcga",
		"prescribedDose": "900",
		"drugName": "Cyclophosphane",
		"id": "19d3b016-37b3-4cd9-8ead-68e4ae3a15c4"
	}
}
```

(also, Cyclophosphane is CID2907, need to add that to the translation table)

**Comment by prismofeverything** [comment]
I am going to add a feature to protograph to ignore edges with missing from
or to values, which would fix this issue.

**Comment by prismofeverything** [comment]
Okay this has been fixed in the latest build. Let me know if you find any other edges with missing values, we can regenerate those too.
