### ISSUE TITLE
Variant GIDs to long

### ISSUE THREAD

**Issue by kellrott** [biostream/bmeg-etl#95]
Error found in `bmeg_data/mc3/mc3.Variant.Vertex.json`

```
2018/02/22 07:03:09 Insert Error: WiredTigerIndex::insert: key too large to index, failing  5499 { : "variant:GRCh37:11:1264584:1270026:CCCCCCAGTGCTGACCACCACCGCCACCACACCTGCAGCCACCAGCAACACAGTGACTCCCTCCTCTGCCCTAGGGACCACCCACACACCCCCAGTGCCGAACACCATGGCCACCA..." }
```

**Comment by bwalsh** [comment]
@kellrott @prismofeverything : let me know your thoughts

Possible alternatives:
* Use HGVS `g.` notation. ( not 100% sure that will reduce the length for this example len~5442, needs testing)  I do have some [code](https://github.com/ohsu-comp-bio/g2p-aggregator/blob/v0.8/harvester/location_normalizer.py#L49) to create a generic g. notation
* Use another ID - for example clingen's cannonical allele, but this will depend on a consistent lookup 
   see [allele registry](http://reg.clinicalgenome.org/allele/CA321211).  This will need a strategy for encoding 'misses'
 * use the existing scheme, but hash the key

**Comment by prismofeverything** [comment]
I can truncate the field in protograph, should remain an unambiguous id at
100 characters, for example.

**Comment by kellrott** [comment]
Maybe determine max key length, and hash if the string is longer then that

**Comment by prismofeverything** [comment]
Fixed here: https://github.com/biostream/bmeg-etl/pull/96/files
