### ISSUE TITLE
ccle.ResponseCurve.json is corrupt

### ISSUE THREAD

**Issue by buchanae** [biostream/bmeg-etl#99]
In exastack swift, biostream/biostream/ccle.ResponseCurve.json has a corrupt first line, which looks like a partially written JSON string.

```
cat biostream/ccle/ccle.ResponseCurve.json | head
value": -76.79124451}, {"type": "ACTIVITY_AREA", "value": 1.7113}], "sample": "NCIH
```

**Comment by prismofeverything** [comment]
Ah yeah, this sometimes happens with the swift client apparently. I will
regenerate.
